LUNA_STAGING := $(HOME)/webos/staging

all:
	@echo "Nothing to do"
	
install:
	@mkdir -p $(LUNA_STAGING)/include/sysmgr-ipc
	install -m 0644 messages/*.h $(LUNA_STAGING)/include/sysmgr-ipc

clean:
	@rm -rf $(LUNA_STAGING)/include/sysmgr-ipc

